import type { AuditReport } from '@promptos/shared';
import { capitalize } from './utils.js';

export function formatMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  addSummarySection(lines, report);

  if (report.scan.totalCalls === 0) {
    lines.push('_No LLM API calls detected._');
    lines.push('');
    return lines.join('\n');
  }

  addProviderSection(lines, report);
  addCostDriversSection(lines, report);
  addDeepAnalysisSection(lines, report);

  lines.push(`_Generated by PromptOS v${report.version} on ${report.timestamp}_`);
  lines.push('');
  return lines.join('\n');
}

function addSummarySection(lines: string[], report: AuditReport): void {
  const { scan, cost } = report;
  lines.push('# PromptOS AI Audit Report');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Files scanned | ${scan.scannedFiles} |`);
  if (scan.skippedFiles > 0) {
    lines.push(`| Files skipped | ${scan.skippedFiles} |`);
  }
  lines.push(`| LLM API calls detected | ${scan.totalCalls} |`);
  lines.push(`| Scan duration | ${(scan.scanDurationMs / 1000).toFixed(1)}s |`);
  lines.push(`| **Estimated monthly cost** | **$${cost.totalMonthlyCostUSD.toFixed(2)}** |`);
  lines.push('');
}

function addProviderSection(lines: string[], report: AuditReport): void {
  lines.push('## Provider Usage');
  lines.push('');
  lines.push('| Provider | Calls | Monthly Cost | Share |');
  lines.push('|----------|-------|-------------|-------|');
  for (const [name, summary] of Object.entries(report.cost.byProvider)) {
    lines.push(
      `| ${capitalize(name)} | ${summary.callCount} | $${summary.totalMonthlyCostUSD.toFixed(2)} | ${summary.percentage}% |`,
    );
  }
  lines.push('');
}

function addCostDriversSection(lines: string[], report: AuditReport): void {
  const { cost, scan } = report;
  if (cost.topCostDrivers.length === 0) return;

  lines.push('## Top Cost Drivers');
  lines.push('');
  lines.push('| # | Location | Method | Monthly Cost |');
  lines.push('|---|----------|--------|-------------|');
  const limit = Math.min(10, cost.topCostDrivers.length);
  for (let i = 0; i < limit; i++) {
    const driver = cost.topCostDrivers[i];
    if (!driver) continue;
    const call = scan.calls[driver.callIndex];
    if (!call) continue;
    lines.push(
      `| ${i + 1} | \`${call.filePath}:${call.line}\` | \`${call.method}\` | $${driver.monthlyCostUSD.toFixed(2)} |`,
    );
  }
  lines.push('');
}

function addDeepAnalysisSection(lines: string[], report: AuditReport): void {
  if (!report.deepAnalysis) return;

  const { opportunities, totalEstimatedSavingsUSD } = report.deepAnalysis;
  lines.push('## Optimization Opportunities');
  lines.push('');
  lines.push(
    `**${opportunities.length} opportunities found** with estimated savings of **$${totalEstimatedSavingsUSD.toFixed(2)}/month**`,
  );
  lines.push('');

  if (opportunities.length > 0) {
    lines.push('| Severity | Type | Location | Description | Est. Savings |');
    lines.push('|----------|------|----------|-------------|-------------|');
    for (const opp of opportunities) {
      const severityBadge = opp.severity === 'high' ? '**HIGH**' : opp.severity.toUpperCase();
      lines.push(
        `| ${severityBadge} | ${opp.type} | \`${opp.filePath}:${opp.line}\` | ${opp.description} | $${opp.estimatedMonthlySavingsUSD.toFixed(2)}/mo |`,
      );
    }
    lines.push('');
  }
}
